### ISSUE TITLE
The "xray-jira" reporter does not exist. Check the reporter parameter for errors

### ISSUE THREAD

**Issue by alwanof** [Vooha-QualiTlabs/testcafe-reporter-xray-jira#4]
I got the following error when I run a test with : `testcafe tests/auth.js --reporter xray-jira`

**Comment by Vooha-QualiTlabs** [comment]
Hi @alwanof , which version have you installed? 

Please use v1.0.4 for now. Seems to have an issue with the latest.

**Comment by alwanof** [comment]
Hi @Vooha-QualiTlabs ,thank you a lot .
Could we make a Zoom meeting as a Paid consultation?
if that's OK, please mail me :
free1soft@gmail.com

**Comment by Vooha-QualiTlabs** [comment]
@alwanof  I would be happy to help you. could you post the error details and your system environment variables here?

**Comment by alwanof** [comment]
@Vooha-QualiTlabs  I really appreciate that :) 
here is my simple project (for testing):
https://github.com/alwanof/testcafe-xray
- I am using node 16 and npm 8.15 on Mac 
I still get: reporter does not exist error when running the test

**Comment by Vooha-QualiTlabs** [comment]
@alwanof  thank you for the details, I am able to reproduce the issue on my Windows. I will look into this if I can do any needful.

**Comment by Vooha-QualiTlabs** [comment]
@alwanof  Try `npm install testcafe-browser-provider-browserstack` and run the test once. In this case, the test runs fine. I am not sure though why it is depending on that package. It would be a quick workaround as of now. Thanks!

**Comment by alwanof** [comment]
@Vooha-QualiTlabs thank you 👍 , I applied this solution but it's not working as expected!!
https://www.awesomescreenshot.com/video/12576816?key=a3c9436a964ca8b2b8755994c4d9eb08

**Comment by Vooha-QualiTlabs** [comment]
@alwanof  I see two issues in the video:

- You have to give the test Id of the ticket WP-1750, in the readme file I just used sample test id as XRAY-50. please replace it.
- It shows the browser name as undefined as you are running the test in headless mode, try to run in normal mode.

I hope both of the above solves your issue. Thank you!

**Comment by alwanof** [comment]
I got the same result!, does it work fine on your side? since May cause I am using Mac, I will try windows 
https://www.awesomescreenshot.com/video/12594166?key=4d0034a3493b1c5f607126ad53dcd910

**Comment by Vooha-QualiTlabs** [comment]
@alwanof  okay, I have send you a meeting invitation mail.

**Comment by alwanof** [comment]
@Vooha-QualiTlabs   I accept the invitation. but maybe I am late so kindly if we can schedule another meeting so I can be ready in that time

**Comment by Vooha-QualiTlabs** [comment]
@alwanof I have pushed the latest version which might fix the `undefined` issue.

**Comment by Vooha-QualiTlabs** [comment]
this issue is resolved, good to close this issue
